// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createImage = `-- name: CreateImage :exec
INSERT INTO image (visit_id, filename, original_name, mimetype, size, created_at) VALUES(?, ?, ?, ?, ?,CURRENT_TIMESTAMP)
`

type CreateImageParams struct {
	VisitID      int64
	Filename     string
	OriginalName string
	Mimetype     sql.NullString
	Size         sql.NullInt64
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.ExecContext(ctx, createImage,
		arg.VisitID,
		arg.Filename,
		arg.OriginalName,
		arg.Mimetype,
		arg.Size,
	)
	return err
}

const createVisit = `-- name: CreateVisit :one
INSERT INTO visit (location_id, employee_id, notes, datetime, duration) VALUES (?, ?, ?, ?, ?) RETURNING id
`

type CreateVisitParams struct {
	LocationID int64
	EmployeeID int64
	Notes      sql.NullString
	Datetime   string
	Duration   int64
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createVisit,
		arg.LocationID,
		arg.EmployeeID,
		arg.Notes,
		arg.Datetime,
		arg.Duration,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCustomerById = `-- name: GetCustomerById :one
SELECT id, name FROM customer WHERE id = ?
`

func (q *Queries) GetCustomerById(ctx context.Context, id int64) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerById, id)
	var i Customer
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getLocationById = `-- name: GetLocationById :one
SELECT
	l.name AS location_name,
	c.name AS customer_name,
	c.Id AS customer_id,
	l.id AS location_id
FROM location l
INNER JOIN customer c
ON l.customer_id = c.id
WHERE l.id = ?
`

type GetLocationByIdRow struct {
	LocationName string
	CustomerName string
	CustomerID   int64
	LocationID   int64
}

func (q *Queries) GetLocationById(ctx context.Context, id int64) (GetLocationByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getLocationById, id)
	var i GetLocationByIdRow
	err := row.Scan(
		&i.LocationName,
		&i.CustomerName,
		&i.CustomerID,
		&i.LocationID,
	)
	return i, err
}

const getVisitById = `-- name: GetVisitById :one
SELECT 
	v.datetime AS visit_datetime,  
	v.duration AS visit_duration, 
	c.name customer_name, 
	l.name location_name, 
	e.name employee_name 
FROM visit v
	INNER JOIN location l ON v.location_id = l.id
	INNER JOIN employee e ON e.id = v.employee_id
	INNER JOIN customer c ON c.id = l.customer_id
WHERE v.id = ?
`

type GetVisitByIdRow struct {
	VisitDatetime string
	VisitDuration int64
	CustomerName  string
	LocationName  string
	EmployeeName  string
}

func (q *Queries) GetVisitById(ctx context.Context, id int64) (GetVisitByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getVisitById, id)
	var i GetVisitByIdRow
	err := row.Scan(
		&i.VisitDatetime,
		&i.VisitDuration,
		&i.CustomerName,
		&i.LocationName,
		&i.EmployeeName,
	)
	return i, err
}

const getVisitsByEmployee = `-- name: GetVisitsByEmployee :many
SELECT 
	v.id AS visit_id,  
	e.name AS employee_name, 
	l.name AS location_name
FROM visit v
    INNER JOIN employee e ON v.employee_id = e.id
	INNER JOIN location l ON v.location_id = l.id
WHERE e.id = ?
`

type GetVisitsByEmployeeRow struct {
	VisitID      int64
	EmployeeName string
	LocationName string
}

func (q *Queries) GetVisitsByEmployee(ctx context.Context, id int64) ([]GetVisitsByEmployeeRow, error) {
	rows, err := q.db.QueryContext(ctx, getVisitsByEmployee, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVisitsByEmployeeRow
	for rows.Next() {
		var i GetVisitsByEmployeeRow
		if err := rows.Scan(&i.VisitID, &i.EmployeeName, &i.LocationName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, name FROM customer
`

func (q *Queries) ListCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocations = `-- name: ListLocations :many
SELECT id, name, customer_id FROM location
`

func (q *Queries) ListLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(&i.ID, &i.Name, &i.CustomerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
