version: "3.9"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: ${VT_DB_PORT}
      POSTGRES_USER: ${VT_DB_USER}
      POSTGRES_PASSWORD: ${VT_DB_PASSWORD}
      POSTGRES_DB: ${VT_DB_NAME}

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${VT_DB_USER}
      POSTGRES_PASSWORD: ${VT_DB_PASSWORD}
      POSTGRES_DB: ${VT_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
