version: "3.9"

services:
  caddy:
    image: caddy:2
    restart: always
    ports:
      - "${CADDY_HTTP_PORT}:${CADDY_HTTP_PORT}" # Host:Container
      # - "${CADDY_HTTPS_PORT}:${CADDY_HTTPS_PORT}" # Host:Container
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api

  api:
    env_file: ".env"
    build: .
    ports:
      - "${VT_APP_PORT}:${VT_APP_PORT}"
    depends_on:
      - db
    environment:
      VT_DB_HOST: db
      VT_DB_PORT: "${VT_DB_PORT}"
      VT_DB_USER: "${VT_DB_USER}"
      VT_DB_PASSWORD: "${VT_DB_PASSWORD}"
      VT_DB_NAME: "${VT_DB_NAME}"

  db:
    image: postgres:16
    env_file: ".env"
    restart: always
    environment:
      POSTGRES_USER: "${VT_DB_USER}"
      POSTGRES_PASSWORD: "${VT_DB_PASSWORD}"
      POSTGRES_DB: "${VT_DB_NAME}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${VT_DB_PORT}:${VT_DB_PORT}"

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
