// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sql

import (
	"database/sql"
)

type Customer struct {
	ID   int64
	Name string
}

type Employee struct {
	ID   int64
	Name string
}

type Image struct {
	ID           int64
	VisitID      int64
	Filename     string
	OriginalName string
	Mimetype     sql.NullString
	Size         sql.NullInt64
	CreatedAt    sql.NullString
}

type Location struct {
	ID         int64
	Name       string
	CustomerID int64
}

type Visit struct {
	ID         int64
	LocationID int64
	EmployeeID int64
	Notes      sql.NullString
	Datetime   string
	Duration   int64
}
