// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package sql

import (
	"context"
	"database/sql"
)

const createVisit = `-- name: CreateVisit :exec
INSERT INTO visit (location_id, employee_id, notes, datetime, duration) VALUES (?, ?, ?, ?, ?)
`

type CreateVisitParams struct {
	LocationID int64
	EmployeeID int64
	Notes      sql.NullString
	Datetime   string
	Duration   int64
}

func (q *Queries) CreateVisit(ctx context.Context, arg CreateVisitParams) error {
	_, err := q.db.ExecContext(ctx, createVisit,
		arg.LocationID,
		arg.EmployeeID,
		arg.Notes,
		arg.Datetime,
		arg.Duration,
	)
	return err
}
